### ISSUE TITLE
It doesn't work?

### ISSUE THREAD

**Issue by Noob1e** [bkader/KuiNameplates-WoTLK#1]
I have both "Kui_Nameplates" and "Kui_Nameplates_Auras" in my addons folder, they're active on addons list and I have disabled ElvUI nameplates but Kui Nameplates didn't work for me.

![WoWScrnShot_060521_113357](https://user-images.githubusercontent.com/27544010/120885559-60b27e00-c5f2-11eb-8ab7-21ed805ae3a4.jpg)

**Comment by bkader** [comment]
Any particular reason why they aren't loaded? Are there any missing files? It's weird.

**Comment by bkader** [comment]
Nevermind. `.gitignore` didn't allow several files to be pushed. I just fixed it. Please re-download and check.

**Comment by Noob1e** [comment]
It's working now. Thanks.
