### ISSUE TITLE
[Request] Seperate Font Options

### ISSUE THREAD

**Issue by Noob1e** [bkader/KuiNameplates-WoTLK#2]
Can you seperate the font options for names / healths  / castbars? I mean the font size and offset at least.

**Comment by bkader** [comment]
I will try to do that.

**Comment by bkader** [comment]
> Can you seperate the font options for names / healths / castbars? I mean the font size and offset at least.

Font sizes and offsets have been separated (name, level & health).

**Comment by Noob1e** [comment]
Thanks for adding those options. But now I have 2 more problems.

1) Looks like the level and health texts are attached to the left and right corners. So I can't move them much on X-Y directions. For example, I can't move level or health texts into the middle of the health bar.

![WoWScrnShot_060621_103722](https://user-images.githubusercontent.com/27544010/120916617-4e4c4900-c6b3-11eb-89f0-14ce64930d64.jpg)

2) I did choose "Never show heal..." in "Health display" options but I can't undo that. It's all greyed out.

![WoWScrnShot_060621_103145](https://user-images.githubusercontent.com/27544010/120916553-f31a5680-c6b2-11eb-84f0-0488043e1b23.jpg)

**Comment by bkader** [comment]
Something like this?
![Screenshot_1](https://user-images.githubusercontent.com/4732702/120925697-a42fe980-c6d1-11eb-90d2-9a31abaac9bd.png)

**Comment by Noob1e** [comment]
Yea, something like that.
