### ISSUE TITLE
Nameplates stucked on the screen

### ISSUE THREAD

**Issue by Noob1e** [bkader/KuiNameplates-WoTLK#3]
![WoWScrnShot_060521_124432](https://user-images.githubusercontent.com/27544010/120887519-05858900-c5fc-11eb-9de0-e4b6d4957ea1.jpg)

**Comment by Noob1e** [comment]
It's still same
![WoWScrnShot_060821_221113](https://user-images.githubusercontent.com/27544010/121244621-c0857f00-c8a7-11eb-923c-27c0ed2b6732.jpg)

**Comment by bkader** [comment]
I was unable to reproduce the problem in the current version, not in battlegrounds nor in arenas. Closing this issue.
